// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnrrbjlkgeioxonrgtog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZucnJiamxrZ2Vpb3hvbnJndG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDA4NDIsImV4cCI6MjA2OTQ3Njg0Mn0.csaOxm99uF8Q_f9zyJnqYKsxSApScb7LVdR3qw7RUEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});